# Generated by Django 6.0.2 on 2026-03-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du signalement'),
        ),
        migrations.AddField(
            model_name='match',
            name='report_details',
            field=models.TextField(blank=True, verbose_name='Détails du signalement'),
        ),
        migrations.AddField(
            model_name='match',
            name='report_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison'),
        ),
        migrations.AddField(
            model_name='match',
            name='reported',
            field=models.BooleanField(default=False, verbose_name='Signalé'),
        ),
        migrations.AddField(
            model_name='match',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.team', verbose_name='Signalé par'),
        ),
    ]
