# Generated by Django 6.0.2 on 2026-03-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_report_date_match_report_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registration_fee',
            field=models.IntegerField(default=1000, verbose_name="Frais d'inscription (CDF)"),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Preuve de paiement'),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_validated',
            field=models.BooleanField(default=False, verbose_name='Paiement validé'),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, verbose_name='Nom de votre équipe'),
        ),
    ]
