# Generated by Django 6.0.2 on 2026-03-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_competition_registration_fee_team_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_extra_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buts extérieur (prolongation)'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tirs au but extérieur'),
        ),
        migrations.AddField(
            model_name='match',
            name='first_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_leg_match', to='core.match', verbose_name='Match aller'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_extra_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buts domicile (prolongation)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tirs au but domicile'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_leg',
            field=models.CharField(choices=[('unique', 'Match unique'), ('aller', 'Match aller'), ('retour', 'Match retour')], default='unique', max_length=10, verbose_name='Type de match'),
        ),
    ]
