# Generated by Django 6.0.2 on 2026-03-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source_away_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_to_away', to='core.match', verbose_name='Source équipe extérieur (vainqueur de)'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_home_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_to_home', to='core.match', verbose_name='Source équipe domicile (vainqueur de)'),
        ),
    ]
