# Generated by Django 6.0.2 on 2026-03-09 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match_source_away_match_match_source_home_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True, verbose_name='Abréviation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+243999999999'", regex='^\\+?\\d{9,15}$')], verbose_name='WhatsApp'),
        ),
    ]
