# Generated by Django 6.0.2 on 2026-03-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_team_abbreviation_alter_team_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du report'),
        ),
        migrations.AddField(
            model_name='match',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_matches', to=settings.AUTH_USER_MODEL, verbose_name='Reporté par'),
        ),
        migrations.AddField(
            model_name='match',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ancienne date'),
        ),
        migrations.AddField(
            model_name='match',
            name='rescheduled_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison du report'),
        ),
    ]
