# Generated by Django 6.0.2 on 2026-02-28 22:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la compétition')),
                ('format_type', models.CharField(choices=[('ucl', 'Format UEFA Champions League'), ('group', 'Groupes + Élimination directe')], default='ucl', max_length=10, verbose_name='Format')),
                ('max_teams', models.IntegerField(default=36, verbose_name="Nombre max d'équipes")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('registration_open', models.BooleanField(default=True, verbose_name='Inscriptions ouvertes')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétition',
                'verbose_name_plural': 'Compétitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('league', 'Phase de ligue'), ('playoff', 'Barrages'), ('round_16', '8e de finale'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('final', 'Finale')], max_length=50, verbose_name='Phase')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=False, verbose_name='Phase active')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.competition', verbose_name='Compétition')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Nom du joueur')),
                ('team_name', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('abbreviation', models.CharField(max_length=3, unique=True, verbose_name='Abréviation')),
                ('whatsapp', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+243999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Logo')),
                ('played', models.IntegerField(default=0, verbose_name='Matchs joués')),
                ('wins', models.IntegerField(default=0, verbose_name='Victoires')),
                ('draws', models.IntegerField(default=0, verbose_name='Nuls')),
                ('losses', models.IntegerField(default=0, verbose_name='Défaites')),
                ('goals_for', models.IntegerField(default=0, verbose_name='Buts marqués')),
                ('goals_against', models.IntegerField(default=0, verbose_name='Buts encaissés')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['-points', '-goals_for'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Score domicile')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Score extérieur')),
                ('is_played', models.BooleanField(default=False, verbose_name='Match joué')),
                ('is_forfeit', models.BooleanField(default=False, verbose_name='Forfait')),
                ('scheduled_date', models.DateTimeField(verbose_name='Date prévue')),
                ('played_date', models.DateTimeField(blank=True, null=True, verbose_name='Date jouée')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='match_screenshots/', verbose_name="Capture d'écran")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.phase', verbose_name='Phase')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='Équipe extérieur')),
                ('forfeit_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfeits', to='core.team', verbose_name='Équipe forfait')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='Équipe domicile')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du groupe')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.competition', verbose_name='Compétition')),
                ('teams', models.ManyToManyField(related_name='groups', to='core.team', verbose_name='Équipes')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
    ]
