# Generated by Django 6.0.2 on 2026-03-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_away_extra_time_match_away_penalties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='payment_proof',
        ),
    ]
