# Generated by Django 6.0.2 on 2026-03-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueDrawSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tirage Ligue', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_draw_sessions', to='core.competition')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueDrawPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_pairs_a', to='core.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_pairs_b', to='core.team')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.leaguedrawsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'team_a', 'team_b'), name='unique_league_pair_per_session')],
            },
        ),
    ]
