# Generated by Django 6.0.2 on 2026-03-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_leaguedrawsession_leaguedrawpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.PositiveIntegerField(default=1, verbose_name='Journée'),
        ),
    ]
