# Generated by Django 6.0.2 on 2026-03-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match_matchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('player', 'Joueur'), ('superadmin', 'Super Admin'), ('organisateur', 'Organisateur'), ('paiement', 'Modérateur Paiements'), ('match', 'Gestionnaire Matchs')], default='player', max_length=20),
        ),
    ]
