# Generated by Django 6.0.2 on 2026-03-25 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_match_rescheduled_at_match_rescheduled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=5, verbose_name='Abréviation'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'competition'), name='unique_abbreviation_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('whatsapp', 'competition'), name='unique_whatsapp_per_competition'),
        ),
    ]
