# Generated by Django 4.2.30 on 2026-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_team_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='registration_fee',
            field=models.IntegerField(default=2500, verbose_name="Frais d'inscription (CDF)"),
        ),
    ]
