# Generated by Django 4.2.30 on 2026-09-23 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Preuve de paiement'),
        ),
    ]
