# Generated by Django 4.2.30 on 2026-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_team_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Règlement accepté'),
        ),
        migrations.AddField(
            model_name='team',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation"),
        ),
    ]
